/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "idleserver.h"

bool_t
xdr_twonos (XDR *xdrs, twonos *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->no1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->no2))
		 return FALSE;
	return TRUE;
}
