/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "idleserver.h"
#include<stdlib.h>
#include<stdio.h>

float *
getcpu_1_svc(void *argp, struct svc_req *rqstp)
{
	static float  result;
	FILE *fp;
	/*
	 * insert server code here
	 */
        system("mpstat > info.temp");
        fp=fopen("info.temp", "r");
        fseek(fp,-6 , SEEK_END);
        fscanf(fp,"%f",&result);
        fclose(fp);

	return &result;
}

int *
addnos_1_svc(twonos *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
        result=argp->no1+argp->no2;
	return &result;
}
