/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "idleserver.h"


void
idleserver_1(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	char *getcpu_1_arg;
	int  *result_2;
	twonos  addnos_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, idleserver, idleserverversion, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = getcpu_1((void*)&getcpu_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("%f",*result_1);
	result_2 = addnos_1(&addnos_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	idleserver_1 (host);
exit (0);
}
